export interface GuestProps {
  img: string;
  link: string;
  name: string;
  gig: string[];
}

export const headliners: GuestProps[] = [
  {
    img: "05-taahliah.jpg",
    link: "akataahliah/",
    name: "TAAHLIAH",
    gig: ["https://ra.co/events/1494126"],
  },
  {
    img: "08-martyn.jpg",
    link: "mbootyspoon/",
    name: "Martyn Bootyspoon",
    gig: ["https://ra.co/events/1515781"],
  },
  {
    img: "09-2-shell.jpg",
    link: "twoshell/",
    name: "Two Shell",
    gig: ["https://ra.co/events/1523162"],
  },
  {
    img: "10-glimmerman.jpg",
    link: "_glimmerman_/",
    name: "Glimmerman",
    gig: ["https://ra.co/events/1523165"],
  },
  {
    img: "10-sweeney.jpg",
    link: "rory_sweeney123/",
    name: "Rory Sweeney",
    gig: ["https://ra.co/events/1546542", "https://ra.co/events/1523165"],
  },
  {
    img: "14-satyr.jpg",
    link: "amorsatyr/",
    name: "Amor Satyr",
    gig: ["https://ra.co/events/1550775"],
  },
  {
    img: "15-plus-one.jpg",
    link: "__plus__one__/",
    name: "Plus One",
    gig: [
      "https://www.eventbrite.com/e/plant-bassd-presents-plus-one-with-e-the-artist-lychee-tickets-384796585947",
    ],
  },
  {
    img: "19-dj-pacifier.jpg",
    link: "dj_pacifier/",
    name: "DJ Pacifier",
    gig: ["https://ra.co/events/1576857"],
  },
  {
    img: "24-mell.jpg",
    link: "dj_mellg/",
    name: "DJ Mell G",
    gig: ["https://ra.co/events/1585832"],
  },
  {
    img: "27-luxe-pic.jpg",
    link: "luxe____________/",
    name: "Luxe",
    gig: ["https://ra.co/events/1606239"],
  },
  {
    img: "30-kessler-cover.jpg",
    link: "____kessler/",
    name: "Kessler",
    gig: ["https://ra.co/events/1640764"],
  },
  {
    img: "31-dj-bok.jpg",
    link: "dj__bok/",
    name: "Bok Bok",
    gig: ["https://ra.co/events/1639467"],
  },
];

export const guestList: GuestProps[] = [
  {
    img: "smiff.jpg",
    link: "smiffmusic/",
    name: "SMIFF",
    gig: ["https://ra.co/events/1484531", "https://ra.co/events/1485121"],
  },
  {
    img: "3-jackjosh.jpg",
    link: "jackjoshualindsay/",
    name: "JackJosh",
    gig: ["https://ra.co/events/1484531"],
  },
  {
    img: "03-cleanup-crew.jpg",
    link: "cleanupedi/",
    name: "Cleanup Edi",
    gig: ["https://ra.co/events/1484531"],
  },
  {
    img: "02-stanger.jpg",
    link: "nina_stanger",
    name: "Nina Stanger",
    gig: ["https://ra.co/events/1485121"],
  },
  {
    img: "das-booty.jpg",
    link: "das_booty_rave/",
    name: "Ten Pence Criminal",
    gig: ["https://ra.co/events/1500809"],
  },
  {
    img: "02-feena.jpg",
    link: "feena_mmm/",
    name: "Feena",
    gig: ["https://ra.co/events/1463880", "https://ra.co/events/1480079"],
  },
  {
    img: "02-fio-fa.jpg",
    link: "fiofa__/",
    name: "Fio Fa",
    gig: ["https://ra.co/events/1480079"],
  },
  {
    img: "05-lucky-dip.jpg",
    link: "_luckydip_/",
    name: "Lucky Dip",
    gig: [
      "https://ra.co/events/1494126",
      "https://ra.co/events/1505400",
      "https://ra.co/events/1581956",
      "https://ra.co/events/1719245",
    ],
  },
  {
    img: "05-sweet-philly.jpg",
    link: "phillyholmes_/",
    name: "Sweet Philly",
    gig: [
      "https://ra.co/events/1494126",
      "https://ra.co/events/1515781",
      "https://ra.co/events/1533360",
    ],
  },
  {
    img: "06-ytp.jpg",
    link: "ytp.aiff/",
    name: "YTP",
    gig: ["https://ra.co/events/1500809"],
  },
  {
    img: "07-casement.jpg",
    link: "case_ment/",
    name: "Casement",
    gig: [
      "https://ra.co/events/1505400",
      "https://ra.co/events/1570572",
      "https://ra.co/events/1628390",
    ],
  },
  {
    img: "07-iso-yso.jpg",
    link: "iso.yso/",
    name: "Iso Yso",
    gig: ["https://ra.co/events/1505400", "https://ra.co/events/1628390"],
  },
  {
    img: "07-roo.jpg",
    link: "roohoneychild/",
    name: "Roo Honeychild",
    gig: [
      "https://ra.co/events/1463880",
      "https://ra.co/events/1505400",
      "https://ra.co/events/1570572",
    ],
  },
  {
    img: "08-oisin.jpg",
    link: "inspectorcampbellbap/",
    name: "oBrother",
    gig: [
      "https://ra.co/events/1463880",
      "https://ra.co/events/1480079",
      "https://ra.co/events/1484531",
      "https://ra.co/events/1485121",
      "https://ra.co/events/1500809",
      "https://ra.co/events/1515781",
      "https://ra.co/events/1523162",
      "https://ra.co/events/1523165",
      "https://ra.co/events/1530814",
      "https://ra.co/events/1546542",
      "https://www.eventbrite.com/e/plant-bassd-presents-plus-one-with-e-the-artist-lychee-tickets-384796585947",
      "https://ra.co/events/1570572",
      "https://ra.co/events/1576857",
      "https://www.eventbrite.ie/e/plant-bassd-presents-organica-tickets-399512531737",
      "https://ra.co/events/1606239",
      "https://ra.co/events/1628390",
      "https://ra.co/events/1639467",
      "https://ra.co/events/1640764",
      "https://ra.co/events/1699420",
      "https://ra.co/events/1719245",
      "https://ra.co/events/1737600",
    ],
  },
  {
    img: "michael.jpg",
    link: "Michaelsaverage/",
    name: "michael average",
    gig: [
      "https://ra.co/events/1523165",
      "https://www.eventbrite.ie/e/plant-bassd-presents-organica-tickets-399512531737",
    ],
  },
  {
    img: "08-helena.jpg",
    link: "helena_h3l3na/",
    name: "H3L3NA",
    gig: ["https://ra.co/events/1515781", "https://ra.co/events/1640764"],
  },
  {
    img: "09-sosi.jpg",
    link: "itsjustsosi/",
    name: "sosi",
    gig: ["https://ra.co/events/1523162"],
  },
  {
    img: "09-behra.jpg",
    link: "b3hra/",
    name: "b3hra",
    gig: ["https://ra.co/events/1523162"],
  },
  {
    img: "10-sohotsospicy.jpg",
    link: "sohotsospicy/",
    name: "sohotsospicy",
    gig: ["https://ra.co/events/1523165"],
  },
  {
    img: "10-ayolxi.jpg",
    link: "ayolxi/",
    name: "Ayolxi",
    gig: ["https://ra.co/events/1523165"],
  },
  {
    img: "11-jenn-hession.jpg",
    link: "jennhession/",
    name: "Jenn Hession",
    gig: ["https://ra.co/events/1533360"],
  },
  {
    img: "11-silky.jpg",
    link: "silkyklub/",
    name: "Silky Klub",
    gig: ["https://ra.co/events/1533360"],
  },
  {
    img: "12-petfood.jpg",
    link: "petfoodbaby/",
    name: "DJ Petfood",
    gig: ["https://ra.co/events/1530814"],
  },
  {
    img: "12-cabbage.jpg",
    link: "apieceofcabbage/",
    name: "Miss Cabbage",
    gig: [
      "https://ra.co/events/1530814",
      "https://ra.co/events/1581956",
      "https://ra.co/events/1628390",
    ],
  },
  {
    img: "12-sara.jpg",
    link: "sarrawild/",
    name: "Sarra Wild",
    gig: ["https://ra.co/events/1530814"],
  },
  {
    img: "13-julia.jpg",
    link: "julialouiseknifefist/",
    name: "Julia Louise KnifeFist",
    gig: ["https://ra.co/events/1546542"],
  },
  {
    img: "14-doubt.jpg",
    link: "doubt_fld/",
    name: "Doubt",
    gig: ["https://ra.co/events/1550775", "https://ra.co/events/1570572"],
  },
  {
    img: "14-skillis.jpg",
    link: "skillis___/",
    name: "Skillis",
    gig: ["https://ra.co/events/1485121", "https://ra.co/events/1550775"],
  },
  {
    img: "15-lychee.jpg",
    link: "lychee800/",
    name: "Lychee",
    gig: [
      "https://www.eventbrite.ie/e/plant-bassd-presents-organica-tickets-399512531737",
      "https://www.eventbrite.com/e/plant-bassd-presents-plus-one-with-e-the-artist-lychee-tickets-384796585947",
    ],
  },
  {
    img: "15-e.jpg",
    link: "etheartistdublin/",
    name: "E The Artist",
    gig: [
      "https://www.eventbrite.com/e/plant-bassd-presents-plus-one-with-e-the-artist-lychee-tickets-384796585947",
      "https://ra.co/events/1533360",
    ],
  },
  {
    img: "16-vaj-power.jpg",
    link: "vaj.power/",
    name: "VAJ.Power",
    gig: ["https://ra.co/events/1570572"],
  },
  {
    img: "16-dj-egg.jpg",
    link: "dj__egg/",
    name: "DJ Egg",
    gig: ["https://ra.co/events/1570572"],
  },
  {
    img: "18-hellokt.jpg",
    link: "katiietynan/",
    name: "HelloKT",
    gig: ["https://www.eventbrite.ie/e/plant-bassd-presents-organica-tickets-399512531737"],
  },
  {
    img: "18-dump.jpg",
    link: "ryandumpdwyerr/",
    name: "D*mp",
    gig: ["https://www.eventbrite.ie/e/plant-bassd-presents-organica-tickets-399512531737"],
  },
  {
    img: "18-curtisy.jpg",
    link: "itscurtisy/",
    name: "Curtisy",
    gig: ["https://www.eventbrite.ie/e/plant-bassd-presents-organica-tickets-399512531737"],
  },
  {
    img: "19-katelate.jpg",
    link: "katelate.dj/",
    name: "KateLate",
    gig: ["https://ra.co/events/1576857", "https://ra.co/events/1595479"],
  },
  {
    img: "20-melly.jpg",
    link: "sssmmeelllyyy/",
    name: "Melly",
    gig: ["https://ra.co/events/1581956"],
  },
  {
    img: "20-joey.jpg",
    link: "joeymousepads/",
    name: "Joey Mousepads",
    gig: ["https://ra.co/events/1581956"],
  },
  {
    img: "24-nyla.jpg",
    link: "dylanyla/",
    name: "Nyla",
    gig: ["https://ra.co/events/1585832"],
  },
  {
    img: "24-kopi.jpg",
    link: "kopi___o/",
    name: "KOPI O",
    gig: ["https://ra.co/events/1585832"],
  },
  {
    img: "25-sky.jpg",
    link: "rowanmcilvride/",
    name: "Mackerelsky",
    gig: ["https://ra.co/events/1595479"],
  },
  {
    img: "25-poog1rl.jpg",
    link: "poog1rl/",
    name: "poog1rl",
    gig: ["https://ra.co/events/1595479", "https://ra.co/events/1628390"],
  },
  {
    img: "27-naafi.jpg",
    link: "naafi_________/",
    name: "Naafi",
    gig: ["https://ra.co/events/1606239"],
  },
  {
    img: "28-diessa.jpg",
    link: "diessa__/",
    name: "diessa",
    gig: ["https://ra.co/events/1628390"],
  },
  {
    img: "28-fluffie.jpg",
    link: "djfluffie/",
    name: "DJ FLUFFIE",
    gig: ["https://ra.co/events/1628390"],
  },
  {
    img: "28-inez.jpg",
    link: "inez.gla/",
    name: "Inez",
    gig: ["https://ra.co/events/1628390"],
  },
  {
    img: "28-marbles.jpg",
    link: "marky.marbles/",
    name: "Marky Marbles",
    gig: ["https://ra.co/events/1628390"],
  },
  {
    img: "29-elfz.jpg",
    link: "matt_.elfz/",
    name: "ELFZ",
    gig: ["https://ra.co/events/1636490"],
  },
  {
    img: "29-danyo.jpg",
    link: "danielmaherr/",
    name: "Danyo",
    gig: ["https://ra.co/events/1636490"],
  },
  {
    img: "29-sea.jpg",
    link: "seaurch1n/",
    name: "SeaUrchin",
    gig: ["https://ra.co/events/1636490"],
  },
  {
    img: "29-mia.jpg",
    link: "fatbogwalrus/",
    name: "MIA",
    gig: ["https://ra.co/events/1636490"],
  },
  {
    img: "30-bleen.jpg",
    link: "fionnblaney/",
    name: "Bleen",
    gig: ["https://ra.co/events/1640764"],
  },
  {
    img: "31-elanda.jpg",
    link: "elanda111/",
    name: "Elanda",
    gig: ["https://ra.co/events/1639467"],
  },
  {
    img: "31-daksh.jpg",
    link: "slibbiibaby/",
    name: "Daksh",
    gig: ["https://ra.co/events/1639467"],
  },
  {
    img: "32-kavari.jpg",
    link: "kavari_____/",
    name: "Kavari",
    gig: ["https://ra.co/events/1685076"],
  },
  {
    img: "32-mm.jpg",
    link: "max_filesize/",
    name: "MM",
    gig: ["https://ra.co/events/1685076"],
  },
  {
    img: "32-akumu.jpg",
    link: "a.ku.mu/",
    name: "Akumu",
    gig: ["https://ra.co/events/1685076"],
  },
  {
    img: "32-de-grandi.jpg",
    link: "ndegrandi/",
    name: "De Grandi",
    gig: ["https://ra.co/events/1685076"],
  },
  {
    img: "33-white-prata.jpg",
    link: "white.prata/",
    name: "White Prata",
    gig: ["https://ra.co/events/1694179"],
  },
  {
    img: "33-lolly.jpg",
    link: "flirty.lollypop33/",
    name: "FLIRTY.LOLLYPOP33",
    gig: ["https://ra.co/events/1694179"],
  },
  {
    img: "33-hotwater.jpg",
    link: "djhotwaterbottle/",
    name: "DJ Hotwaterbottle",
    gig: ["https://ra.co/events/1694179"],
  },
  {
    img: "33-effua.jpg",
    link: "3ffua/",
    name: "EFFUA",
    gig: ["https://ra.co/events/1694179"],
  },
  {
    img: "34-brenda.jpg",
    link: "brend4_internacional/",
    name: "Brenda",
    gig: ["https://ra.co/events/1699420"],
  },
  {
    img: "34-shaz.jpg",
    link: "dj.shahrazadi/",
    name: "Shahrazadi",
    gig: ["https://ra.co/events/1699420"],
  },
  {
    img: "34-ell.jpg",
    link: "quarterpoundernocheese/",
    name: "Quarterpoundernocheese",
    gig: ["https://ra.co/events/1699420"],
  },
  {
    img: "34-strawbby.jpg",
    link: "strawb.bby/",
    name: "strawb.bby",
    gig: ["https://ra.co/events/1699420"],
  },
  {
    img: "34-clo.jpg",
    link: "cloallenn/",
    name: "CLO",
    gig: ["https://ra.co/events/1699420"],
  },
  {
    img: "35-crrdr.jpg",
    link: "c0rred0r/",
    name: "CRRDR",
    gig: ["https://ra.co/events/1719245"],
  },
  {
    img: "35-loreto.jpg",
    link: "loretolihuenn",
    name: "Loreto",
    gig: ["https://ra.co/events/1719245"],
  },
  {
    img: "35-indigo.jpg",
    link: "indigokorres",
    name: "Indigo",
    gig: ["https://ra.co/events/1719245"],
  },
  {
    img: "39-ten-years-lost.jpg",
    link: "tenyearslost",
    name: "Ten Years Lost",
    gig: ["https://ra.co/events/1737600"],
  },
  {
    img: "39-arusa.jpg",
    link: "arusaqureshi",
    name: "Arusa Qureshi",
    gig: ["https://ra.co/events/1737600"],
  },
];
