#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

npm run lint ||
(
        echo "ESLint Check Failed. Make the required changes listed above, add changes and try to commit again."
        false; 
)

npm run test ||
(
        echo "Test stage Failed."
        false; 
)

# If everything passes... Now we can commit
echo "✅✅ Commit passed"

git add .

# add --no-verify to bypass
# git commit -m "updating sw.js" --no-verify